<a href="https://colab.research.google.com/github/eduardorebelove/Perceptron/blob/main/SklearnPronto.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [118]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import mean_squared_error, accuracy_score


In [119]:
class PrintMSECallback:
    def __init__(self):
        self.mse_per_epoch = []

    def __call__(self, mlp, X_train, y_train):
        y_pred_train = mlp.predict(X_train)
        mse = mean_squared_error(y_train, y_pred_train)
        self.mse_per_epoch.append(mse)
        print(f'Iteração {len(self.mse_per_epoch)}, Erro Quadrático Médio (MSE): {mse}')

In [120]:
# Carregar dados dos CSVs
X = np.array(list(csv.reader(open('data_input.csv', 'r'), delimiter=','))).astype('float')
y = np.array(list(csv.reader(open('data_output.csv', 'r'), delimiter=','))).astype('float')


In [121]:
# Dividir os dados em conjuntos de treinamento e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Configurar o modelo MLPClassifier com callback personalizado
mlp = MLPClassifier(hidden_layer_sizes=(64, 10), max_iter=1, warm_start=True, solver='adam', random_state=42, learning_rate_init=0.001)
callback = PrintMSECallback()


In [122]:
# Treinar o modelo por iterações, imprimindo o MSE a cada iteração
for epoch in range(1500):
    mlp.fit(X_train, y_train)
    callback(mlp, X_train, y_train)

# Fazer predições nos dados de teste
y_pred = mlp.predict(X_test)
# Calcular o erro quadrático médio (MSE) final
mse = mean_squared_error(y_test, y_pred)
print(f'Erro Quadrático Médio (MSE) final: {mse}')

# Calcular a acurácia (erros e acertos)
accuracy = accuracy_score(y_test, y_pred)
print(f'Acurácia: {accuracy * 100}%')


# Exibir o número de iterações realizadas
print(f'Número de iterações: {len(callback.mse_per_epoch)}')

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1) reached and the optimization hasn't converged yet.
  warnings.warn(


Iteração 1, Erro Quadrático Médio (MSE): 0.4809523809523809
Iteração 2, Erro Quadrático Médio (MSE): 0.46845238095238095
Iteração 3, Erro Quadrático Médio (MSE): 0.4565476190476191
Iteração 4, Erro Quadrático Médio (MSE): 0.44523809523809527
Iteração 5, Erro Quadrático Médio (MSE): 0.43809523809523815
Iteração 6, Erro Quadrático Médio (MSE): 0.42023809523809524
Iteração 7, Erro Quadrático Médio (MSE): 0.4083333333333334
Iteração 8, Erro Quadrático Médio (MSE): 0.3815476190476191
Iteração 9, Erro Quadrático Médio (MSE): 0.36547619047619045
Iteração 10, Erro Quadrático Médio (MSE): 0.34464285714285714
Iteração 11, Erro Quadrático Médio (MSE): 0.3380952380952381
Iteração 12, Erro Quadrático Médio (MSE): 0.3220238095238095
Iteração 13, Erro Quadrático Médio (MSE): 0.3071428571428572
Iteração 14, Erro Quadrático Médio (MSE): 0.2970238095238095
Iteração 15, Erro Quadrático Médio (MSE): 0.28750000000000003
Iteração 16, Erro Quadrático Médio (MSE): 0.27380952380952384
Iteração 17, Erro Quadrát

In [75]:
print("Dados de Entrada:")
print(X)
print("Dados de Saída:")
print(y)

correct = 0
incorrect = 0

for i in range(len(X)):
    output_layer = mlp.predict([X[i]])
    if np.argmax(output_layer) == np.argmax(y[i]):
        correct += 1
    else:
        incorrect += 1

print("Treino concluído na iteração:", mlp.n_iter_)
print("Quantidade de Acertos:", correct)
print("Quantidade de Erros:", incorrect)

print("Valores onde a rede neural aprendeu:")
for i in range(len(X)):
    output_layer = mlp.predict([X[i]])
    if np.argmax(output_layer) == np.argmax(y[i]):
        print("Entrada:", X[i], "Saída:", output_layer, "Correto!")
    else:
        print("Entrada:", X[i], "Saída:", output_layer, "Erro!")

Dados de Entrada:
[[0. 1. 1. ... 1. 1. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 1. 1. 0.]
 ...
 [0. 1. 1. ... 1. 1. 0.]
 [0. 1. 1. ... 1. 0. 0.]
 [0. 0. 1. ... 1. 0. 0.]]
Dados de Saída:
[[0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 ...
 [0. 1. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
Treino concluído na iteração: 1500
Quantidade de Acertos: 200
Quantidade de Erros: 10
Valores onde a rede neural aprendeu:
Entrada: [0. 1. 1. 1. 1. 1. 1. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 1. 0.
 0. 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 1. 0.
 0. 1. 0. 0. 0. 0. 1. 0. 0. 1. 1. 1. 1. 1. 1. 0.] Saída: [[0 0 0 0 0 0 0 0 0 1]] Correto!
Entrada: [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.
 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.
 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.] Saída: [[0 0 0 0 0 0 0 0 1 0]] Correto!
Entrada: [0. 0. 1. 1. 1. 0. 0. 0. 1. 1. 0

In [102]:
def imprimir_pesos_com_ruido_e_resultados(mlp, X, y, desvio_padrao=0.01):
    # Predições com os pesos com ruído (corrigido)
    y_pred_ruido = []
    for i in range(len(X)):
        ativacao = X[i]  # Começa com a entrada da amostra
        for j in range(len(mlp.coefs_)):
            pesos_com_ruido = mlp.coefs_[j] + np.random.normal(0, desvio_padrao, mlp.coefs_[j].shape)
            biases_com_ruido = mlp.intercepts_[j] + np.random.normal(0, desvio_padrao, mlp.intercepts_[j].shape)
            ativacao = np.dot(ativacao, pesos_com_ruido) + biases_com_ruido  # Propaga a ativação
            if j < len(mlp.coefs_) - 1:  # Aplica a função de ativação (exceto na última camada)
                ativacao = np.maximum(0, ativacao)  # ReLU (ou outra função de ativação)
        y_pred_ruido.append(np.argmax(ativacao))  # Escolhe a classe com maior ativação

    # Convert y_pred_ruido to numpy array for comparison
    y_pred_ruido = np.array(y_pred_ruido)

    # If 'y' is one-hot encoded, extract class indices
    if y.ndim == 2:
        y = np.argmax(y, axis=1)

    acertos_ruido = np.sum(y_pred_ruido == y)
    erros_ruido = len(y) - acertos_ruido

    print("\nResultados:")
    print(f"  Acertos com ruído: {acertos_ruido} de {len(y)}")
    print(f"  Erros com ruído: {erros_ruido} de {len(y)}")

In [127]:
imprimir_pesos_com_ruido_e_resultados(mlp, X, y, desvio_padrao=0.02)


Resultados:
  Acertos com ruído: 206 de 210
  Erros com ruído: 4 de 210


In [129]:
imprimir_pesos_com_ruido_e_resultados(mlp, X, y, desvio_padrao=0.05)


Resultados:
  Acertos com ruído: 205 de 210
  Erros com ruído: 5 de 210


In [130]:
imprimir_pesos_com_ruido_e_resultados(mlp, X, y, desvio_padrao=0.1)


Resultados:
  Acertos com ruído: 203 de 210
  Erros com ruído: 7 de 210


In [131]:
imprimir_pesos_com_ruido_e_resultados(mlp, X, y, desvio_padrao=0.3)


Resultados:
  Acertos com ruído: 103 de 210
  Erros com ruído: 107 de 210
